title: reawan's Homepage
page-top-title: reawan
top-section-bg-text: Radio and Television Studies
home-subtitle: reawan &ensp;|&ensp;reawan 
copyright-text: '&copy; reawan 2023-2025. All Rights Reserved.'
